[package]
name = "java-language-server"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "/dev/null"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = { version = "1.0.127" }
