module(name = "bazel_java_vscode")

# TODO https://github.com/bazel-contrib/rules_bazel_integration_test for bazel testing
# Will also help automate --deleted_packages management.
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")
bazel_dep(name = "aspect_rules_js", version = "3.0.3")
bazel_dep(name = "aspect_rules_ts", version = "3.9.2")
bazel_dep(name = "rules_java", version = "8.6.2")
bazel_dep(name = "rules_jvm_external", version = "6.6")
bazel_dep(name = "rules_nodejs", version = "6.7.5")
bazel_dep(name = "hermetic_cc_toolchain", version = "3.1.1")
bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "bazel_skylib", version = "1.7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
# REPIN=1 bazel run @maven//:pin
maven.install(
    artifacts = [
        "com.google.code.gson:gson:2.11.0",
        "jakarta.annotation:jakarta.annotation-api:3.0.0",
        # Test dependencies
        # TODO Update to JUnit 5
        "junit:junit:4.13.2",
        "org.hamcrest:hamcrest:2.2",
        # Benchmarking
        "org.openjdk.jmh:jmh-core:1.37",
        "org.openjdk.jmh:jmh-generator-annprocess:1.37",
        # Extra checks
        "com.uber.nullaway:nullaway:0.12.1"
    ],
    lock_file = "//:maven_install.json",
    version_conflict_policy = "pinned",
    fail_if_repin_required = True,
)
use_repo(maven, "maven")

java_toolchains = use_extension("@rules_java//java:extensions.bzl", "toolchains")
use_repo(
    java_toolchains,
    "remote_java_tools",
    "remote_java_tools_darwin_arm64",
    "remote_java_tools_darwin_x86_64",
    "remote_java_tools_linux",
    "remote_java_tools_windows",
    "remotejdk21_linux_toolchain_config_repo",
    "remotejdk21_macos_toolchain_config_repo",
    "remotejdk21_macos_aarch64_toolchain_config_repo",
    "remotejdk21_win_toolchain_config_repo",
)
register_toolchains(
    "@remotejdk21_linux_toolchain_config_repo//:all",
    "@remotejdk21_macos_toolchain_config_repo//:all",
    "@remotejdk21_macos_aarch64_toolchain_config_repo//:all",
    "@remotejdk21_win_toolchain_config_repo//:all",
)

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(
    node_repositories = {
        "26.5.0-darwin_arm64": ("node-v26.5.0-darwin-arm64.tar.xz", "node-v26.5.0-darwin-arm64", "48231d6204eca6be13e6c5184dfdffa1d64ad88880364cc2cfb198f872cb2b13"),
        "26.5.0-darwin_amd64": ("node-v26.5.0-darwin-x64.tar.xz", "node-v26.5.0-darwin-x64", "8cf6704df7d8bfbfb2e290b23de0e7da9569e6741391035eaa0ddcb50fd8d3d0"),
        "26.5.0-linux_arm64": ("node-v26.5.0-linux-arm64.tar.xz", "node-v26.5.0-linux-arm64", "036df0b49662ebb350eb56f1cac603699b1e9ed1e2603ee129fefda473479030"),
        "26.5.0-linux_ppc64le": ("node-v26.5.0-linux-ppc64le.tar.xz", "node-v26.5.0-linux-ppc64le", "d8042da56b7b8ae15b65239efc642918f904d689e0c96a2943c782bd7c126e1b"),
        "26.5.0-linux_s390x": ("node-v26.5.0-linux-s390x.tar.xz", "node-v26.5.0-linux-s390x", "cb6c7942a0ef6ac6275d39aba2de2cf58c6037e5529d065cf4ec834500746802"),
        "26.5.0-linux_amd64": ("node-v26.5.0-linux-x64.tar.xz", "node-v26.5.0-linux-x64", "9f619528f1db5ddc41dccf54211066fb42228d69a156733c69cb9d6cc92e358c"),
        "26.5.0-windows_amd64": ("node-v26.5.0-win-x64.zip", "node-v26.5.0-win-x64", "d3b2277dbcccfdf24ef6302928f64f484cff1d77a6d3caa3a28f4d20ce9158f6"),
    },
    node_version = "26.5.0",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")

npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
    npmrc = "//:.npmrc",
)
use_repo(npm, "npm")

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")
use_repo(pnpm, "pnpm")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    ts_version_from = "@npm//:typescript/resolved.json",
)
use_repo(rules_ts_ext, "npm_typescript")

toolchains = use_extension("@hermetic_cc_toolchain//toolchain:ext.bzl", "toolchains")
use_repo(toolchains, "zig_sdk")

register_toolchains(
    "@zig_sdk//toolchain:linux_amd64_gnu.2.31",
    "@zig_sdk//toolchain:linux_arm64_gnu.2.31",
    "@zig_sdk//toolchain:windows_amd64",
    "@zig_sdk//toolchain:windows_arm64",
)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    versions = ["1.97.1"],
    edition = "2024",
)
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//:Cargo.toml"],
)
use_repo(crate, "crates")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "maven_cli",
    sha256 = "80ffca22aed9e8b9713a232f3394fd81d7f20322df75efdb2b047dbd3e3a23bb",
    urls = ["https://dlcdn.apache.org/maven/maven-3/3.9.16/binaries/apache-maven-3.9.16-bin.tar.gz"],
    strip_prefix = "apache-maven-3.9.16",
    add_prefix = "src",
    build_file_content = """
alias(
    name = "bin",
    actual = "src/bin/mvn",
    visibility = ["//visibility:public"],
)
filegroup(
    name = "bin_files",
    srcs = glob(["src/**/*"], exclude = ["src/bin/mvn"]),
    visibility = ["//visibility:public"],
)
    """,
)
