name: "CI"
on:
  push:
    branches:
      - main
  # Pull request
  pull_request:
    types:
      # Newly opened
      - opened
      # Updated (excludes change of base branch)
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: "${{ github.workflow }}-test"
          repository-cache: true
      - run: bazel test //...
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            .bazel/testlogs/**/test.log
            .bazel/testlogs/**/test.xml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: "${{ github.workflow }}-build"
          repository-cache: true
      - run: bazel build //extension/vsix:java_bazel_language_support --stamp
      - uses: actions/upload-artifact@v4
        with:
          name: java-bazel-language-support-vsix
          path: .bazel/bin/extension/vsix/java_bazel_language_support.vsix
